### ISSUE TITLE
com.gorisse.thomas.sceneform.light.LightEstimationConfig.getMode()' on a null object reference

### ISSUE THREAD

**Issue by Arun1947** [SceneView/sceneform-android#207]
Hi,
I used scenform version 1.17.1 and now I have updated the
dependency to 1.20.1 then I get this error. Code running on older version, but crashing inside the dependency code when updated.
  java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.ar.core.Config$LightEstimationMode com.gorisse.thomas.sceneform.light.LightEstimationConfig.getMode()' on a null object reference
        at com.google.ar.sceneform.ArSceneView.onBeginFrame(ArSceneView.java:524)
        at com.google.ar.sceneform.SceneView.doFrameNoRepost(SceneView.java:466)
        at com.google.ar.sceneform.SceneView.doFrame(SceneView.java:450)
        at com.google.ar.sceneform.ArSceneView.doFrame(ArSceneView.java:550)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
        at android.view.Choreographer.doCallbacks(Choreographer.java:849)
        at android.view.Choreographer.doFrame(Choreographer.java:775)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:257)
        at android.app.ActivityThread.main(ActivityThread.java:8218)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

**Comment by Arun1947** [comment]
Do I need to update all implemented codes to use the update (1.20.1)?  i used   <com.google.ar.sceneform.ArSceneView as my view in old sdk (1.17.1)

**Comment by ThomasGorisse** [comment]
Please use the 1.20.2 to see if your non fragment usage is fixed.

**Comment by ThomasGorisse** [comment]
Should be available in minutes

**Comment by Arun1947** [comment]
@ThomasGorisse Thanks...This crash issue fixed while changed to 1.20.2..
 But the issue is color change in the .glb and gif file added (in node).

**Comment by ThomasGorisse** [comment]
This must due to the `LightEstimationMode` which, by default, enables the `LightEstimationMode.ENVIRONMENTAL_HDR` using the back camera but disable it with the front camera because ARCore lights estimations are not available on it.

This affects the model rendered colors since your real environment might not be the same as the front camera emulated one.

Try this to disable the all light estimations :
`arSceneView.lightEstimationConfig = LightEstimationConfig.DISABLED`
or the Ambient Intensity which might be available on the front camera but please confirm here
`arSceneView.lightEstimationConfig = LightEstimationConfig.AMBIENT_INTENSITY`

**Comment by Arun1947** [comment]
I have a node with image view, I added a gif inside it, the red color inside the gif is orange when it loads.
I used arSceneView.lightEstimationConfig = LightEstimationConfig.AMBIENT_INTENSITY & DISABLED -- but not change

**Comment by ThomasGorisse** [comment]
@RGregat It looks like the filmic issue we had with Filament.
Is is possible that the filmic color is not applied in a non ArFragment usage?

**Comment by ThomasGorisse** [comment]
Fix: #311
