### ISSUE TITLE
Load glTF resource occured an fatal exception

### ISSUE THREAD

**Issue by wxj978566042** [SceneView/sceneform-android#282]
I have a glTF resource which can show in https://gltf-viewer.donmccurdy.com/ normally. An exception occured when loading by sceneform, here is the log trace, hopeful if anyone could give the reason.

```
Process: com.test.arnavigator, PID: 26840
    java.lang.AssertionError: Resource path contains a scheme but should be relative, uri: (data:application/octet-stream;base64,AwAOAAYAAwAAAA4AJgAlACcAJgAkACUAJAAjACUAJAAiACMAIwAgACEAIwAiACAAIAACACEAIAABAAIAHgAdAB8AHgAcAB0AHAAbAB0AHAAaABsAGwAYABkAGwAaABgAGAAAABkAGAAOAAAAFgAVABcAFgAUABUAFAATABUAFAASABMAEwAQABEAEwASABAAEAANABEAEAAPAA0ABgANAA8ABgAOAA0ADAAJAAoADAALAAkACgAHAAgACgAJAAcABwAFAAgABwAEAAUABQADAAYABQAEAAMAAgAAAAMAAgABAAAAv0PyQAAAAADZWhnBAAAAAAAAgL8AAAAAfnRiP+CHfT+/Q/LAAAAAANlaGcEAAAAAAACAvwAAAAAUXOw94Id9P5WfGsEAAAAAXrrvwAAAAAAAAIC/AAAAAM3BHDzSNmI/lZ8awQAAAABeuu9AAAAAAAAAgL8AAAAAzcEcPOhI7j3BLRrBAAAAAASt+kAAAAAAAACAvwAAAADgd508UrfTPXo2/cAAAAAAEOkYQQAAAAAAAIC/AAAAAIoB0j20wJ48v0PywAAAAADZWhlBAAAAAAAAgL8AAAAAFFzsPRAGHjwCyBjBMVQzpQHeAkEAAAAAAACAvwAAAAAwaPw85Ni6PbwiBMEAAAAAUYMXQQAAAAAAAIC/AAAAAFVWuT28df48n1kWwQAAAABBSAhBAAAAAAAAgL8AAAAANZ8uPW4Poj3yjAnBAAAAAOQUFUEAAAAAAACAvwAAAADWv6A9zAswPU3nEsEAAAAA3EsNQQAAAAAAAIC/AAAAAGBoXz3kTok9l5AOwQAAAACSohFBAAAAAAAAgL8AAAAAnzKIPQw6YT2VnxpBAAAAAF6670AAAAAAAACAvwAAAAD0jH0/6EjuPZWfGkEAAAAAXrrvwAAAAAAAAIC/AAAAAPSMfT/SNmI/v0PyQAAAAADZWhlBAAAAAAAAgL8AAAAAfnRiPxAGHjx6Nv1AAAAAABDpGEEAAAAAAACAvwAAAADPv2U/tMCePMEtGkEAAAAABK36QAAAAAAAAIC/AAAAAEQUez9St9M9vCIEQQAAAABRgxdBAAAAAAAAgL8AAAAAMNVoP7x1/jwCyBhBMVQzpQHeAkEAAAAAAACAvwAAAAC0HHg/5Ni6PfKMCUEAAAAA5BQVQQAAAAAAAIC/AAAAAAToaz/MCzA9n1kWQQAAAABBSAhBAAAAAAAAgL8AAAAAEhZ1P24Poj2XkA5BAAAAAJKiEUEAAAAAAACAvwAAAACp+W4/DDphPU3nEkEAAAAA3EsNQQAAAAAAAIC/AAAAAHgJcj/kTok9wS0aQQAAAAAErfrAAAAAAAAAgL8AAAAARBR7PxaJZT96Nv1AAAAAABDpGMEAAAAAAACAvwAAAADPv2U//gl7PwLIGEEAAAAAAd4CwQAAAAAAAIC/AAAAAMUceD/gpGg/vCIEQTFUM6VRgxfBAAAAAAAAgL8AAAAAMNVoP0oMeD+fWRZBAAAAAEFICMEAAAAAAACAvwAAAAASFnU/GL5rP/KMCUEAAAAA5BQVwQAAAAAAAIC/AAAAAAToaz9K/3Q/TecSQQAAAADcSw3BAAAAAAAAgL8AAAAAeAlyPyrWbj+XkA5BAAAAAJKiEcEAAAAAAACAvwAAAACp+W4/WOxxP3o2/cAAAAAAEOkYwQAAAAAAAIC/AAAAAIoB0j3+CXs/wS0awQAAAAAErfrAAAAAAAAAgL8AAAAA4HedPBaJZT+8IgTBAAAAAFGDF8EAAAAAAACAvwAAAABVVrk9Sgx4PwLIGMExVDOlAd4CwQAAAAAAAIC/AAAAADBo/DzgpGg/8owJwQAAAADkFBXBAAAAAAAAgL8AAAAA1r+gPUj/dD+fWRbBAAAAAEFICMEAAAAAAACAvwAAAAA1ny49Gr5rP5eQDsEAAAAAkqIRwQAAAAAAAIC/AAAAAJ8yiD1Y7HE/TecSwQAAAADcSw3BAAAAAAAAgL8AAAAAYGhfPSrWbj8=)
        at com.google.ar.sceneform.rendering.LoadRenderableFromFilamentGltfTask.getUriFromMissingResource(LoadRenderableFromFilamentGltfTask.java:90)
        at com.google.ar.sceneform.rendering.LoadRenderableFromFilamentGltfTask.lambda$new$0(LoadRenderableFromFilamentGltfTask.java:38)
        at com.google.ar.sceneform.rendering.-$$Lambda$LoadRenderableFromFilamentGltfTask$vcYlGe0YU3gPMDTWm0GtFOwoNDY.apply(Unknown Source:6)
        at com.google.ar.sceneform.rendering.RenderableInstance.createFilamentAssetModelInstance(RenderableInstance.java:166)
        at com.google.ar.sceneform.rendering.RenderableInstance.<init>(RenderableInstance.java:123)
        at com.google.ar.sceneform.rendering.Renderable.createInstance(Renderable.java:254)
        at com.google.ar.sceneform.Node.setRenderable(Node.java:924)
        at com.aliyun.ailabs.arnavigator.ArNavigatorUI.renderTest(ArNavigatorUI.java:285)
        at com.aliyun.ailabs.arnavigator.ArNavigatorUI.lambda$initNavFragment$0$ArNavigatorUI(ArNavigatorUI.java:232)
        at com.aliyun.ailabs.arnavigator.-$$Lambda$ArNavigatorUI$swYNftoxRZq77mIsgnwXHocbIzw.onTapPlane(Unknown Source:2)
        at com.google.ar.sceneform.ux.BaseArFragment.onSingleTap(BaseArFragment.java:703)
        at com.google.ar.sceneform.ux.BaseArFragment.access$000(BaseArFragment.java:67)
        at com.google.ar.sceneform.ux.BaseArFragment$1.onSingleTapUp(BaseArFragment.java:206)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:794)
        at com.google.ar.sceneform.ux.BaseArFragment.onPeekTouch(BaseArFragment.java:653)
        at com.google.ar.sceneform.TouchEventSystem.onTouchEvent(TouchEventSystem.java:129)
        at com.google.ar.sceneform.Scene.onTouchEvent(Scene.java:349)
        at com.google.ar.sceneform.SceneView.onTouchEvent(SceneView.java:111)
        at android.view.View.dispatchTouchEvent(View.java:15199)
```

**Comment by grassydragon** [comment]
Hi!
I guess that you URL may be incorrect.

**Comment by wxj978566042** [comment]
> uri

Firstly I have tried to change models to load, however the model downloaded in https://market.pmnd.rs/model/macbook also occurred this exception. Maybe it's a bug, please have a look.  Here is the code

```
ModelRenderable.builder()
            .setSource(this, Uri.parse(glbPath))
            .setIsFilamentGltf(true)
            .setAsyncLoadEnabled(false)
            .build().thenAccept(new Consumer<ModelRenderable>() {
            @Override
            public void accept(ModelRenderable modelRenderable) {
                modelRenderable.setShadowCaster(false);
                modelRenderable.setShadowReceiver(false);

                TransformableNode transformableNode = new TransformableNode(arFragment.getTransformationSystem());
                transformableNode.setLocalScale(new Vector3(0.5f, 0.5f, 0.5f));
                transformableNode.setLocalPosition(new Vector3(0f, -1f, -1 * (count % 20)));
                try {
                    Log.d(TAG, "setRenderable start...");
                    // exception occurred here...
                    transformableNode.setRenderable(modelRenderable);
                    Log.d(TAG, "setRenderable end...");
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                transformableNode.setParent(arSceneView.getScene());
                transformableNode.select();
            }
        });
```

**Comment by grassydragon** [comment]
It seams this is a current limitation of Sceneform and it can't load glTF models where everything is stored in the text format with the `.gltf` extension because decoding the octet streams isn't implemented: https://github.com/SceneView/sceneform-android/blob/5b5ae1f511a032d224b1678eb4b7befdc0e5bc11/core/src/main/java/com/google/ar/sceneform/rendering/LoadRenderableFromFilamentGltfTask.java#L88
As a workaround for now you can convert models to the binary format with `.glb` extension using this website: https://glb-packer.glitch.me/
I have successfully converted and loaded the MacBook model.

**Comment by ThomasGorisse** [comment]
It's true.
The fact is also that we prefer standardizing  the glb format instead of gltf for those repos since its usage advantages are too small and doesn't bring great things for our use case in front of the folder structure read complexity.
Exemple: res/raw, url, file download are cleaner for single file format.

Someone integrated a gltf to glb in his app and post it in Issues/Discussion section.

Please link it here if you find it or even better, create a PR with a sample of conversion.
