### ISSUE TITLE
Crash when using HandMotionView

### ISSUE THREAD

**Issue by memostark** [SceneView/sceneform-android#314]
I migrated from Scenform 1.5 to this new fork version "1.20.4".

I have the hand layout included in sceneform like this:

```
<FrameLayout
          android:id="@+id/sceneform_hand_layout"
          android:layout_width="0dp"
          android:layout_height="0dp"
          android:clipChildren="false"
          android:elevation="8dp"
          android:visibility="gone"
          app:layout_constraintBottom_toBottomOf="parent"
          app:layout_constraintEnd_toEndOf="parent"
          app:layout_constraintStart_toStartOf="parent"
          app:layout_constraintTop_toBottomOf="@id/toolbar">

          <com.google.ar.sceneform.ux.HandMotionView
              android:id="@+id/sceneform_hand_image"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:foregroundGravity="center"
              android:scaleType="center"
              android:src="@drawable/sceneform_hand_phone" />
</FrameLayout>
```

This worked fine with the old Sceneform but with this fork I get this error when setting visibility to visible:

``` 
   java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getWidth()' on a null object reference
        at com.google.ar.sceneform.ux.HandMotionAnimation.applyTransformation(HandMotionAnimation.java:48)
        at android.view.animation.Animation.initializeInvalidateRegion(Animation.java:1147)
        at android.view.View.applyLegacyAnimation(View.java:23447)
        at android.view.View.draw(View.java:23569)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
        at android.view.View.draw(View.java:23904)
        at android.view.View.updateDisplayListIfDirty(View.java:22776)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.updateDisplayListIfDirty(View.java:22762)
        at android.view.View.draw(View.java:23631)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.draw(View.java:23904)
        at com.android.internal.policy.DecorView.draw(DecorView.java:1284)
        at android.view.View.updateDisplayListIfDirty(View.java:22776)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:579)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:585)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:662)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:5042)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4749)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3866)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
        at android.view.Choreographer.doFrame(Choreographer.java:744)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
```

**Comment by ThomasGorisse** [comment]
Change your HandMotionView id:
https://github.com/SceneView/sceneform-android/blob/master/ux/src/main/res/layout/sceneform_instructions_plane_discovery.xml#L9

**Comment by memostark** [comment]
Thank you. it's fixed. I also had to change the id of the parent `FrameLayout` to handMotionLayout.
