### ISSUE TITLE
Can't change material of glb.

### ISSUE THREAD

**Issue by memostark** [SceneView/sceneform-android#327]
Following the instructions in #163 to change the material of a glb file (in this case I just want to change the color), I'm getting a different error when setting the material.
```
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:278)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:284)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:669)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:642)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:484)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:571)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:590)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:452)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.set(ArrayList.java:453)
        at com.google.ar.sceneform.rendering.RenderableInstance.setMaterial(RenderableInstance.java:415)
        at com.google.ar.sceneform.rendering.RenderableInstance.setMaterial(RenderableInstance.java:405)
        at com.google.ar.sceneform.rendering.RenderableInstance.setMaterial(RenderableInstance.java:397)
```

Here is the code
```
Node arrow = new Node();
arrow.setRenderable(renderable);
anchorNode.addChild(arrow);

RenderableInstance renderableInstance = arrow.getRenderableInstance();
Material changedMaterial = renderableInstance.getMaterial();
changedMaterial.setInt("baseColorIndex", 0);
changedMaterial.setFloat3("baseColorTint", new Color(android.graphics.Color.parseColor(color)));

renderableInstance.setMaterial(changedMaterial);
```

The renderable was previously loaded from a glb. The last line throws the exception. The 3D model is visible on the screen but without the desired color.

**Comment by memostark** [comment]
Thank you, the models show with the expected color, however, the `java.lang.IndexOutOfBoundsException` was still being thrown. I removed the last line `renderableInstance.setMaterial(changedMaterial);` and the exception was gone and the models still displayed correctly.

Do you have any resource to know more about the material parameters: baseColorTint, baseColorFactor, etc?

**Comment by ThomasGorisse** [comment]
You should have a look in the material parameters directly within https://github.com/google/filament
