### ISSUE TITLE
HDREnvironment crash when destroy is called

### ISSUE THREAD

**Issue by Catah97** [SceneView/sceneform-android#335]
We found out that app crash when BaseArFragment.onDestroy is called.

Stack
Caused by: java.lang.IllegalStateException: Calling method on destroyed Texture
        at com.google.android.filament.Texture.getNativeObject(Texture.java:1228)
        at com.google.android.filament.Engine.destroyTexture(Engine.java:582)
        at com.gorisse.thomas.sceneform.material.TextureKt.destroy(Texture.kt:18)
        at com.gorisse.thomas.sceneform.environment.HDREnvironment.destroy(HDREnvironment.kt:74)
        at com.google.ar.sceneform.SceneView.destroyScene(SceneView.java:258)
        at com.google.ar.sceneform.SceneView.destroy(SceneView.java:243)
        at com.google.ar.sceneform.ArSceneView.destroy(ArSceneView.java:370)
        at com.google.ar.sceneform.ux.BaseArFragment.destroy(BaseArFragment.java:304)
        at com.google.ar.sceneform.ux.BaseArFragment.onDestroy(BaseArFragment.java:293)

It happends when arSceneView.environment is set via HDRLoader.loadEnvironment.
Down bellow sending our fix.
```
        lifecycleScope.launch {
            arSceneView.environment = setEnvironment(requireContext())
        }
```
```
@SuppressLint("ResourceType")
suspend fun setEnvironment(context: Context): HDREnvironment? {
    return HDRLoader.loadEnvironment(context, context.getResourceUri(R.raw.comfy_cafe_2k))?.apply {
        /**
         * SceneForm (1.20.5) bug -- this is work around
         * App crash when [HDREnvironment.destroy]. It is because cubemap and skyboxEnvironment are same object.
         * When HDREnvironment is created by [HDRLoader.loadEnvironment] this flag is not set so I have to do it manually.
         */
        sharedCubemap = true
    }
}
```

I think that bug is here 
```
@JvmOverloads
fun HDRLoader.createEnvironment(
    hdrBuffer: Buffer,
    specularFilter: Boolean = defaultSpecularFilter
) = createTexture(Filament.engine, hdrBuffer)?.use { hdrTexture ->
    Filament.iblPrefilter.equirectangularToCubemap(hdrTexture)
}?.let { cubemap ->
    HDREnvironment(cubemap = cubemap, skyboxEnvironment = cubemap, specularFilter = specularFilter)
}
```

Cubemap and skyboxEnvironment are same object and when `HDREnvironment.destory` is called app crash.

**Comment by ThomasGorisse** [comment]
Thanks for the great report. Your right about the reason why it occurs.

Could you make a quick PR to add this:
```kotlin 
if (skyboxEnvironment != cubemap)
```
https://github.com/SceneView/sceneform-android/blob/954162854b2ca84b40c6068b6a314437c17f6506/core/src/main/java/com/gorisse/thomas/sceneform/environment/HDREnvironment.kt#L74-L75
That should be ok for `sharedCubemap = true` case.
Thanks

**Comment by Catah97** [comment]
PR created here 
https://github.com/SceneView/sceneform-android/pull/336
