### ISSUE TITLE
Can't change material of glb: RenderableInstance.getMaterial() on a null object reference

### ISSUE THREAD

**Issue by vjixy** [SceneView/sceneform-android#373]
Following the instructions in [](https://github.com/SceneView/sceneform-android/issues/327) to change the material of a glb file (in this case I just want to change the color), I'm getting a different error when setting the material.
`E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.ar.sceneform.rendering.Material com.google.ar.sceneform.rendering.RenderableInstance.getMaterial()' on a null object reference
        at com.google.ar.sceneform.samples.gltf.MainActivity.onTapPlane(MainActivity.java:465)
        at com.google.ar.sceneform.ux.BaseArFragment.onSingleTap(BaseArFragment.java:703)
        at com.google.ar.sceneform.ux.BaseArFragment.access$000(BaseArFragment.java:67)
        at com.google.ar.sceneform.ux.BaseArFragment$1.onSingleTapUp(BaseArFragment.java:206)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:758)
        at com.google.ar.sceneform.ux.BaseArFragment.onPeekTouch(BaseArFragment.java:653)
        at com.google.ar.sceneform.TouchEventSystem.onTouchEvent(TouchEventSystem.java:129)
        at com.google.ar.sceneform.Scene.onTouchEvent(Scene.java:349)
        at com.google.ar.sceneform.SceneView.onTouchEvent(SceneView.java:111)
        at android.view.View.dispatchTouchEvent(View.java:14369)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3200)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3200)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3200)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3200)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3200)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3200)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3200)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3200)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4177)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
        at android.view.View.dispatchPointerEvent(View.java:14633)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6352)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6146)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5633)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5690)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5656)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5808)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5664)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5865)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5637)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5690)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5656)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5664)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5637)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8493)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8444)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8395)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8628)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
E/MessageQueue-JNI:     at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:222)
        at android.app.ActivityThread.main(ActivityThread.java:8089)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)`

Here is the code 

`   @Override
    public void onTapPlane(HitResult hitResult, Plane plane, MotionEvent motionEvent) {
        if (model == null || viewRenderable == null) {
            Toast.makeText(this, "Loading...", Toast.LENGTH_SHORT).show();
            return;
        }

        Anchor anchor = hitResult.createAnchor();
        AnchorNode anchorNode = new AnchorNode(anchor);
        anchorNode.setParent(arFragment.getArSceneView().getScene());
        
        
//        Here the iserted code
        Color color = new Color(android.graphics.Color.rgb(0, 0, 255));
        Renderable renderable = anchorNode.getRenderable();
        Node test_node = new Node();
        test_node.setRenderable(renderable);
        anchorNode.addChild(test_node);
        RenderableInstance renderableInstance = test_node.getRenderableInstance();
        Material changedMaterial = renderableInstance.getMaterial();
        changedMaterial.setInt("baseColorIndex", 0);
        changedMaterial.setFloat3("baseColorFactor", color);
    /////////////////////////////////////
        
        TransformableNode model = new TransformableNode(arFragment.getTransformationSystem());
        model.setParent(anchorNode);
        
        model.setRenderable(this.model)
                .animate(true).start();
        model.select();
        
        Node titleNode = new Node();

        titleNode.setParent(model);
        titleNode.setEnabled(false);
        titleNode.setLocalPosition(new Vector3(0.0f, 1.0f, 0.0f));
        
        titleNode.setRenderable(viewRenderable);
        titleNode.setEnabled(true);
        
        if(current_model<max_nb-1) {
            current_model += 1;
            loadModels();
        }

    }`

**Comment by vjixy** [comment]
soo never mind it should be on the model not on the anchornode
`Color color = new Color(android.graphics.Color.rgb(0, 0, 255));
    Renderable renderable = anchorNode.getRenderable();
    Node test_node = new Node();
    test_node.setRenderable(renderable);
    anchorNode.addChild(test_node);
    RenderableInstance renderableInstance = test_node.getRenderableInstance();
    Material changedMaterial = renderableInstance.getMaterial();
    changedMaterial.setInt("baseColorIndex", 0);
    changedMaterial.setFloat3("baseColorFactor", color);`

**Comment by vjixy** [comment]
Sorry for using git issue badly
