### ISSUE TITLE
Camera crash

### ISSUE THREAD

**Issue by mohammadMighani** [SceneView/sceneform-android#383]
Hi i am using V1.21.0
and this is error after a few seconds of running tiger animation sample

```
E/CameraCaptureSession: Session 0: Exception while stopping repeating: 
    android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): cancelRequest:352: Camera device no longer alive
        at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:707)
        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:95)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1006)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:390)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:568)
        at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:233)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.os.ServiceSpecificException: cancelRequest:352: Camera device no longer alive (code 4)
        at android.os.Parcel.readException(Parcel.java:1981)
        at android.os.Parcel.readException(Parcel.java:1913)
        at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:375)
        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:93)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1006) 
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:390) 
        at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:568) 
        at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:233) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
W/CameraDevice(0): Device disconnected.
E/StartedCameraController(0): Device closing due to unexpected device event: DeviceErrorEvent(errorType=ERROR_CAMERA_DISCONNECTED)


```

if i use 1.15 sceneform of google camera will not crashes.

how can i solve this issue?
my mobile: Samsung SM-A520F

**Comment by dexmac221** [comment]
Hi, this error happens to me too, since the latest update of Google Play Services for Ar (1.32). If I downgrade to the 1.31 release the crash goes away. Any news about this issue ?

**Comment by RGregat** [comment]
Not so far, most of our work power goes into the SceneView Repository.
I think I'm from the maintainers the only one who actively is using SceneForm. If I encounter the same issue, I will take a look how to fix it.
