### ISSUE TITLE
No virtual method acquireEnvironmentalHdrCubeMap()

### ISSUE THREAD

**Issue by xSabrina** [SceneView/sceneform-android#418]
Hi,

I'm implementing a simple AR App on Android including the geospatial API right now and I keep running into this error:

java.lang.NoSuchMethodError: No virtual method acquireEnvironmentalHdrCubeMap()[Lcom/google/ar/core/ArImage; in class Lcom/google/ar/core/LightEstimate; or its super classes (declaration of 'com.google.ar.core.LightEstimate'
        at com.gorisse.thomas.sceneform.light.LightEstimationKt.environmentalHdrEnvironmentLights(LightEstimation.kt:394)
        at com.gorisse.thomas.sceneform.light.LightEstimationKt.environmentLightsEstimate(LightEstimation.kt:225)
        at com.google.ar.sceneform.ArSceneView.onBeginFrame(ArSceneView.java:527)
        at com.google.ar.sceneform.SceneView.doFrameNoRepost(SceneView.java:466)
        at com.google.ar.sceneform.SceneView.doFrame(SceneView.java:450)
        at com.google.ar.sceneform.ArSceneView.doFrame(ArSceneView.java:552)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
        at android.view.Choreographer.doCallbacks(Choreographer.java:866)
        at android.view.Choreographer.doFrame(Choreographer.java:792)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

Seems like it's not working with the latest versions of ArCore?
Is there any fix to this?

**Comment by RGregat** [comment]
Hi @xSabrina there is no more update for SceneForm scheduled. The complete manpower is now put into SceneView. 

Do you get the same exception with one of the sample applications?

**Comment by devbridie** [comment]
This is probably due to the removal of [`ArImage`](https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.33.0) in 1.33 in favor of `android.media.Image`. The class file is looking for `acquireEnvironmentalHdrCubeMap()[Lcom/google/ar/core/ArImage` but the signature is actually `acquireEnvironmentalHdrCubeMap()[Landroid/media/Image` after this change.  I think recompiling the library would resolve this.
